# Jekyll configuration

url: "https://yutojubako.github.io"
baseurl: "/maimai.github.io"

theme: minima

title: "Yuto Imai"
author: "Yuto Imai"
email: "ytim8812@keio.jp"
description: "Multimodal AI Researcher & Machine Learning Engineer at Keio University"
max_width: 930px

# Navigation menu
header_pages:
  - about.md
  - resume.md
  - projects.md
  - blog.md

# Social links (for minima theme)
github_username: yutojubako
twitter_username: # Add if you have one

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Minima theme settings
minima:
  skin: auto
  social_links:
    github: yutojubako
    # Add other social platforms as needed

# Site icon
icon: "/static/images/image.png"

# Additional site information
location: "Yokohama, Japan"
institution: "Keio University"
lab: "SMI Lab"
research_focus: "Multimodal AI, Computer Vision, Cross-Modal Retrieval"
