# Jekyll configuration for al-folio

url: "https://yutojubako.github.io"
baseurl: "/maimai.github.io"

remote_theme: alshedivat/al-folio

title: "純米吟醸と和解せよ"
author: "Yuto Imai"
email: "ytim8812@keio.jp"
description: "Machine learning and robotics notes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
